### ISSUE TITLE
Allow setting files and directories as Hidden in Properties

### ISSUE THREAD

**Issue by vaguerant** [joel16/3DShell#10]
Is there any chance the Properties pane could have a checkbox/slider/some kind of on-off mechanism for making files and directories Hidden (in the Windows attribute sense, not the Unix preceding period sense). Some homebrew does respect the attribute and skips showing hidden files, so it'd be nice to be able to hide things that we don't need homebrew to see, like support directories full of data files.

**Comment by joel16** [comment]
Hello, yes this is possible as the 3DS does include a flag for hidden directories. I'll add a toggle to enable/disable showing hidden directories in the next version. Thanks for the suggestion.

**Comment by joel16** [comment]
Added. https://github.com/joel16/3DShell/commit/daa1d59f0793b0ac20db56ac69799cee06054c88
