### ISSUE TITLE
3DShell crash when try exit

### ISSUE THREAD

**Issue by jjckswitch** [joel16/3DShell#13]
3DShell crash system when i push "Home" button to exit. But "Start" button good works and i can exit with start button

P.S Sorry for my English

**Comment by joel16** [comment]
Does this happen all the time? Or do you do something before this happens?

**Comment by jjckswitch** [comment]
everytime

**Comment by joel16** [comment]
Can you give some more information, are you using an old 3DS? are you using the .3dsx version? Are you doing anything before pressing the home button?
Cause I've been using it often on my device and haven't faced this issue.

**Comment by jjckswitch** [comment]
New 3DS XL Eur region, using .cia version, no, i don't do anything before press "HOME" button.

**Comment by joel16** [comment]
Hm, might have made a mistake somewhere. Next release makes sure services are working before granting access to certain permissions so that may just fix this issue. Bare with me for a bit, I'm busy in college so the next release might take a while.

**Comment by OctoNezd** [comment]
+1

_Sent from my LeEco X527 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by joel16** [comment]
Ok can either of you try this build and let me know how it goes?
https://drive.google.com/open?id=0BzIzEQt6k4EEMVRpRXhEZVd5eW8

**Comment by jjckswitch** [comment]
crash when starting app :(
![image](https://user-images.githubusercontent.com/30491079/30321777-a965d51a-97d0-11e7-917b-bfc5e3079c3b.png) 
![image](https://user-images.githubusercontent.com/30491079/30321806-d1930198-97d0-11e7-91ea-335fbed53b9e.png)
N3DS XL Eur, 11.5.0, Luma 8.1.1 , B9S 1.3

**Comment by joel16** [comment]
That's weird. Can you try this build? (Before you try this make sure you delete any "3DShell" folder in /3ds/ or /3ds/data/.
https://drive.google.com/open?id=0BzIzEQt6k4EEdTBmRlVaZWRRUGc

If that also crashes, go to FBI -> SD -> 3ds -> data -> 3DShell
and ensure the following files and folders exist:

config.cfg, /colours/, lastdir.txt, theme.bin, colours.bin, /themes/

**Comment by jjckswitch** [comment]
Works fine, but  it also freezes if i press HOME button..

**Comment by jjckswitch** [comment]
I FOUND PROBLEM! With patch "battery percent in status bar" 3DShell freezes system when i press "HOME BUTTON", but without patch - all works fine..
![image](https://user-images.githubusercontent.com/30491079/30338439-2676ff5a-9805-11e7-90b7-fc0e0272df2b.png)

**Comment by joel16** [comment]
I had a feeling it was an external problem and not 3DShell related. Well, thanks for figuring it out.
That's based on the latest commit btw so you kind of got an early taste of the next version. Anyways I'll close this.
