### ISSUE TITLE
Hard crash

### ISSUE THREAD

**Issue by CecilFF4** [joel16/3DShell#15]
Not sure if this is related to my recently doing a ctrtransfer, but anytime I start up 3DShell on an O2DS I recently hacked (latest b9s/luma/sys fw), it hard crashes. That same app works fine on my other console, an O3DSXL (also on latest stuff). It doesn't matter if I transfer the app data from my O3DS SD card (both consoles have the same movable.sed), reinstall the ticket, or reinstall the app fresh, 3DShell always crashes the 2DS. I've attached a Luma crash dump. I haven't parsed it myself, but maybe you'll have some luck with this. Thanks for your help.
[crash_dump_00000000.zip](https://github.com/joel16/3DShell/files/1291452/crash_dump_00000000.zip)

**Comment by joel16** [comment]
That's really strange. Works fine on one console but not the other.
You are using the CIA correct? Python is being really weird on my px. I can send you a test build tomorrow, and if you can report back that'd be great.

**Comment by joel16** [comment]
Can you try this build and let me know how it goes? It's based on the latest commit.

**Comment by CecilFF4** [comment]
Yes, I was using the CIA version. Sorry I didn't specify that. And no, that CIA you just posted isn't working either (crashes after the homebrew splash dissipates).

I got a couple other glitches on this console, again probably from the ctrtransfer (banners not showing after certain homebrew exit, gifts not unwrapping after certain homebrew exit). I'm gonna keep tackling it from my end. If you figure anything out with that luma dump, please let me know.

**Comment by joel16** [comment]
I don't have time to check that crash dump ATM, but I can tell you there  nothing that would cause 3DShell to crash instantly during start up. I know that well due to multiple times of testing it over and over.

3DShell makes each required file and directory for you even if they don't exist. I have a feeling your ctrtransfer is affecting this. Since you used the new build I posted yesterday, can you make sure there's a 3DShell folder in /3ds/data/. The data files could be the only reason it would crash during boot up.

**Comment by CecilFF4** [comment]
If you do get time to check the dump, would you mind telling me the results?

Also, there was a newly created 3dshell folder in the 3ds/data folder. However, a folder inside named "colours" was spelled wrong. :P

**Comment by deltabeard** [comment]
"colours" is correct English spelling.

**Comment by CecilFF4** [comment]
The :P meant that it was a joke. Sorry if that wasn't clear.

**Comment by deltabeard** [comment]
Dude I nearly got triggered haha

**Comment by joel16** [comment]
Yeah python's being a pain for me. So I'll try to get someone I know to parse the dump and see what it is. However I still have a feeling your issue might not be 3DShell related.

**Comment by joel16** [comment]
Can you try this? https://drive.google.com/open?id=0BzIzEQt6k4EEdTBmRlVaZWRRUGc

Also try enabling the option: "disable exception vectors" in Luma's config. It's known to fuck up sometimes.

**Comment by CecilFF4** [comment]
Well, what do you know. It works. Didn't have to mess with Luma settings at all.

I do have a theory, based on some testing I did. I was doing tests with the ticket for this app and could not get it to install (FBI kept throwing errors). I tried the ticket straight from the CIA (the ticket.bin renamed) and the ticket from my mounted ticket.db using gm9 (yes, the sha for those tickets were different -- no idea why, and it's not just for this app). Turns out I couldn't install either of them previously. Now the CIA ticket does install, and the app works, too (the gm9 version of the ticket does not, still, but that's usually the way it goes).

Thanks for your help!
