### ISSUE TITLE
Not working on old3DS

### ISSUE THREAD

**Issue by jlswbs** [joel16/3DShell#18]
Not working on old3DS only yellow bottom screen (version v2.0 working great)

use latest ninjhax2 and firmware update

**Comment by joel16** [comment]
I'm pretty sure you need Luma3DS to run this. Are you using an older version of homebrew launcher?

**Comment by jlswbs** [comment]
testing both original smealum hb_menu and latest new_hbmenu

is possible post your launcher for test? many thanks

**Comment by joel16** [comment]
I mostly only use CIA, but yeah 3DShell requires some extended permissions (mcuhwc) which can only be accessed with Luma CFW or the latest HB menu.

**Comment by jlswbs** [comment]
hmm problem is know Luma require fw < 11.3.0-36 (Luma cfw working only with very old fw)

im use new fw 11.6.0-39

**Comment by joel16** [comment]
Sadly this won't work with *hax cause it requires extended service access such as mcuhwc and arm9 patches to allow access to CTRNAND.
