### ISSUE TITLE
App freezes on "closing software..." when FTP server is on

### ISSUE THREAD

**Issue by Ryuzaki-MrL** [joel16/3DShell#19]
Open 3DShell, turn on the FTP server, press HOME then close the application. It'll be stuck on "closing software..."

**Comment by joel16** [comment]
I initially intended it to not be able to do that while FTP mode is enabled. However, it seems like a bug that'll I'll need to fix. But now from you can quickly toggle FTP off with select or touching the icon, then exit the app.

**Comment by joel16** [comment]
Has been fixed in the rewrite branch https://github.com/joel16/3DShell/commit/c9769420e0b6e49b4b6229d1485e8a16d5e3095d

Once it's done I will merge to master.
