### ISSUE TITLE
Freeze on properties window

### ISSUE THREAD

**Issue by NateDogg1232** [joel16/3DShell#2]
I'm using an o3DS using A9LH Corbenik CFW and a 32GB SD card (I'm just trying to give as much info as possible)

Whenever trying to view the properties of a file (not a folder/directory), that is the first in the list (in all, not just displayed), the properties window hangs and a hard reboot (holding the power button down) is required to exit the application.

**Comment by NateDogg1232** [comment]
Update: Apparently it's with random files, not just on the top of the list. Came to too fast of a conclusion there. But with those files that crash it, the results are easily replicated, even after a reboot.

**Comment by joel16** [comment]
Hm I'm not sure what's the cause. I literally just tried it myself and went into random directories and checked for file properties I didn't get any crashes. 

Looks like I'm going to have to start logging things pretty soon. Anyways a new test build should be up in a bit, and I've made some minor changes to the way certain flags are handled. Please try it out and let me know if the issue persists.

**Comment by joel16** [comment]
Nvm, you're right it does indeed happen very randomly.

**Comment by joel16** [comment]
Fixed https://github.com/joel16/3DShell/commit/bbc47c94595d60609252cb6eed74b31b7dae2c3e.

**Comment by joel16** [comment]
Should be fixed with https://github.com/joel16/3DShell/releases/tag/v1.0.1
