### ISSUE TITLE
[Suggestion] UI Improvement

### ISSUE THREAD

**Issue by Leafgreen26** [joel16/3DShell#21]
So you know how CTRXplorer has its UI to where you can see a lot more of your SD card? 

https://gbatemp.net/threads/release-ctrxplorer-open-source-sd-file-manager.390353/ 

Well I was thinking that maybe the UI for this application could look sort of like a Windows file explorer:

![image](https://user-images.githubusercontent.com/35386457/35120200-faa8d09e-fc5c-11e7-9db9-94b21bab86c7.png)

Except without the sidebar and details on the side. Just a suggestion. I know that this would take a ton of time and that the themes would have to be changed for it. Love your work btw.

**Comment by joel16** [comment]
The thing is 3DShell is aiming to look like [this](https://www.google.com/search?q=cyanogenmod+file+manager&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjEpqL1xuLYAhUEgK0KHZYoCmIQ_AUICygC&biw=1280&bih=590#imgrc=aihGyswGDB7t-M) Which is based on the design of CyanogenMod's file manager. So this probably won't happen. However, in the future I might be able to implement viewing them in both screens if I get the time.
