### ISSUE TITLE
Fix the highlighted row when scrolling down

### ISSUE THREAD

**Issue by TurdPooCharger** [joel16/3DShell#23]
When you scroll down with enough folders or files, the highlighted row where it denotes the current selectable item does something that is somewhat annoying in appearance IMO.

Let's assume there are 10 folders or files in the current directory you're viewing. You place the highlighted row at item number 10.

You go up with D-Pad or joystick. While your new selected item does up by one, the highlighted row is still at the bottom of the 5 viewable rows.

Can you update the app where pressing up keeps the currently seen 5 items static and the highlighted row only instead goes up by itself until hitting and going past the very first row of those 5?

**Comment by MarcoMartins86** [comment]
I was not sure what were you talking about, but now that I have seen it, I cannot unsee it again. Is somewhat an annoying behavior, although it doesn't break any functionality. Fortunately, I use the app mostly for the FTP, not file browsing.

**Comment by joel16** [comment]
Heh, I didn't bother to respond cause it didn't seem too important of an issue and looked more like a personal preference to me. I guess I can try looking into it, however other features and fixes are prioritized at the moment. I'm also busy with school and other projects, but I'll try to get back to this as soon as I can. Appreciate the feedback.

**Comment by TurdPooCharger** [comment]
No problem. It's not feature breaking issue. Other than that, great program btw. :D

Also, I used yours a lot when bug testing my gm9 script for system apps injections (not just Health & Safety). Yours was first in my cia folder, small sized, and launchable after injection.

It's funny to have 10 installed 3DShell at the same time. Lmao.

**Comment by joel16** [comment]
Fixed in latest beta release.
