### ISSUE TITLE
[Feature Request] While using FTP server

### ISSUE THREAD

**Issue by MarcoMartins86** [joel16/3DShell#24]
While using FTP server it would be nice if the top screen would turn off to save battery since it is just a frozen image that doesn't contribute with any information to the current task.
Also, not sure if possible, but if the FTP server worked with the lit close would be greater.
Even if you don't have the time, thank you for your work as it is already really good.

**Comment by joel16** [comment]
Yes this is possible, I may just dim it to the least possible amount. Thanks for the feedback!

**Comment by MarcoMartins86** [comment]
Nice :)

**Comment by joel16** [comment]
You can press start to turn off display on both screens https://github.com/joel16/3DShell/commit/6471b083823af106c265f09246bce3e3c0c72fc2
