### ISSUE TITLE
small ui suggestions for image preview

### ISSUE THREAD

**Issue by zweilous** [joel16/3DShell#25]
would it be possible to
* make the top bar with the filename optional when selecting an image to preview? it makes sifting through them quicker when they're screen size and i want to see the entire thing at once
* use the left/right buttons when in preview mode to alphabetically go through images in a folder

thanks for this tool. it's literally the only decent one available for viewing images as far as i know

**Comment by joel16** [comment]
The system protection feature has been vaulted for the gallery show/hide since its a more demanding feature.

https://github.com/joel16/3DShell/commit/e1aa2a4a047c036ab45bfaf6e593cd9fe2bf190e

**Comment by joel16** [comment]
Done https://github.com/joel16/3DShell/commit/6471b083823af106c265f09246bce3e3c0c72fc2
