### ISSUE TITLE
NFS/SMB client support?

### ISSUE THREAD

**Issue by sahlberg** [joel16/3DShell#27]
Would be awesome to be able to browse network shares using NFS and or SMB.

libnfs is a mature nfs client that builds on virtually any platform.

libsmb2 is a new client to talk to windows/cifs servers. It is new so it is not as portable as libnfs, yet.

**Comment by joel16** [comment]
Hey, sorry about the late response. The thing is this project still has a lot that needs to be done like file viewing as well as some improvements to gallery and music player so this won't be of any priority right now. Of course being open source it isn't stopping anyone to send a PR either.

**Comment by joel16** [comment]
Considering the console is dying and I'll soon be shifting towards the Switch, I don't think this will happen. The project is open source, so if anyone do want to give this a go feel free to PR.
