### ISSUE TITLE
(problem) when shutting down program in ftp server mode

### ISSUE THREAD

**Issue by zebranco** [joel16/3DShell#28]
being in ftp mode press the home button and close the program and the 3ds is frozen trying to close the program being necessary force to disconnect

**Comment by joel16** [comment]
This has been fixed with the recent re-write. Can you test the latest nightly build from here? http://joel16.github.io be warned some things are currently broken such as moving from nand -> sd or sd -> nand. Also recylce bin and system protection is disabled entirely.

**Comment by zebranco** [comment]
really the night build the problem was really solved thank you very much for everything
