### ISSUE TITLE
Crash when lid closed while mp3 is playing

### ISSUE THREAD

**Issue by Ajun10** [joel16/3DShell#29]
Whenever I play an MP3 w/ 3dShell, then close the lid w/ headphones connected, the audio still plays, but when I'm done, I open the lid, and I just see a black screen, even though the audio is still playing.

**Comment by joel16** [comment]
Yes this is a known issue. I've had interest with other projects recently and haven't had the time to look at it. I'm back to working on this for a bit, so I'll take a look when I get time.

**Comment by Ajun10** [comment]
Okay thanks!

**Comment by joel16** [comment]
Fixed https://github.com/joel16/3DShell/commit/6471b083823af106c265f09246bce3e3c0c72fc2
