### ISSUE TITLE
Searching freezes 3DSX version

### ISSUE THREAD

**Issue by Ryuzaki-MrL** [joel16/3DShell#31]
Confirming or canceling the prompt with any input string freezes the system (holding power required to turn off) on the 3DSX version, running on Luma3DS 9.0 via Download Play on a New 3DS XL (11.7). This is a fresh install (old files removed beforehand).

**Comment by joel16** [comment]
Crap, knew I forgot to check something. Will look into it.

**Comment by joel16** [comment]
Fixed https://github.com/joel16/3DShell/commit/795d14597b157f2027a251d1af9033893df03cd3
You can update using the nightly option.

**Comment by joel16** [comment]
Reopening as this was wrongly reported as working.

**Comment by joel16** [comment]
Fixed for sure now :P https://github.com/joel16/3DShell/commit/6657bb05207e3a939c9d4f129c8e03efe66aec18
