### ISSUE TITLE
Crash when next or prev is selected while mp3 is playing 

### ISSUE THREAD

**Issue by giodude143** [joel16/3DShell#33]
Pressing next or prev causes the app to crashes.

Update: Added a line on menu_music.c fixes the issue. Although some MP3 files still won't play and automatically closes the music player.
[update.txt](https://github.com/joel16/3DShell/files/2230078/update.txt)

**Comment by joel16** [comment]
That shouldn't be it. Audio_StopPlayback is already called in Music_HandleNext(), you're basically calling it twice. Are you using mp3 files?

**Comment by giodude143** [comment]
I see, I removed the Audio_StopPlayback it seems to work fine now. 
Yes I'm using mp3 files.
