### ISSUE TITLE
[Lock Toggle bug] Pause/Resume Music w/ L/R Buttons

### ISSUE THREAD

**Issue by destinedjagold** [joel16/3DShell#34]
It is currently possible to pause/resume the music by clicking both L and R buttons at the same time while the 3DS is on sleep mode, and while the [Start] lock toggle is on.

**Comment by joel16** [comment]
L/R shouldn't pause or resume it's taking a screenshot. I'll fix that quickly.

**Comment by joel16** [comment]
Try with the latest nightly.
