### ISSUE TITLE
Shuffle Loop Decrements

### ISSUE THREAD

**Issue by destinedjagold** [joel16/3DShell#35]
Something seems weird with the shuffle functionality (while on sleep mode). I noticed this earlier today when the app kept on repeating three songs, and (theorizing) the number of songs to loop seems to be decreasing, until it only loops 1 song, and after that song ended, the variable is now 0 so there's no song to loop, and the app crashed

**Comment by joel16** [comment]
Shouldn't happen anymore https://github.com/joel16/3DShell/commit/620b9499bf2f465f2424c75e93f2fd508c78f8c5

**Comment by destinedjagold** [comment]
I am honestly not sure if it's fixed or not as I tried the newest update twice today, but it still crashes at some point. Perhaps the cause is no longer the loop thing.

**Comment by joel16** [comment]
Hm, I'll have to reopen this then. I'll send you a build that logs everything so we get a better idea. I'm busy at the moment so it'll have to wait till the weekend at most.

**Comment by joel16** [comment]
Okay here are the builds that logs data from the music player. I want you to try the one you prefer (cia/3dsx) and play around with it till it crashes. Then send me the log located in /3ds/3DShell/log.txt.

[3DSX](https://drive.google.com/file/d/1KFDXwl7JEDkIGSGxkZ0oyItg4f905USW/view?usp=sharing)
[CIA](https://drive.google.com/file/d/1vfKordMEF5gU2WOQZRRfgeeFQeG-VRnA/view?usp=sharing)

**Comment by joel16** [comment]
SD:/3ds/3DShell/log.txt.

**Comment by destinedjagold** [comment]
[log.txt](https://github.com/joel16/3DShell/files/2394644/log.txt)

Here you go.

**Comment by joel16** [comment]
Can you upload it to some place else? I can't access it.

**Comment by destinedjagold** [comment]
Here you go.

https://drive.google.com/open?id=1IXBwVGsmrlobvX0arQntmAomA5M-uC0Z

**Comment by destinedjagold** [comment]
Ah, the 41 to 40 issue was because I deleted a song.

Anyway, I've backed up a lot of log files every time the app crashes. There's quite a number of them, but I'll be uploading the latest one soon.

Anyway, I find the decrement weird to be quite honest. Is it not possible to create an array of the available songs, randomize it, and use a "foreach"?

**Comment by destinedjagold** [comment]
Picture of the homescreen after the app crashed: https://i.imgur.com/WntfoQL.jpg

Latest log file: https://drive.google.com/open?id=1-M4jzAvVQE-Ga4Hh4mfFEXhrHZoOW1ER

**Comment by joel16** [comment]
I've decided to remove the audio decoder functionality within 3DShell due to lack of time, and motivation. You can use the following alternative which seems to be better supported: https://github.com/Oreo639/LimePlayer3DS
