### ISSUE TITLE
Issue with *hax 3DS

### ISSUE THREAD

**Issue by diegofn** [joel16/3DShell#36]
Hello @joel16 
Thanks for your effort. I want to report an issue starting the 3DShell on my 3DS with *hax 11.7. The app does not start and show the following image.

![dsc_0192](https://user-images.githubusercontent.com/981273/43460170-7effd15a-9495-11e8-8ceb-a3eaf34d9608.JPG)

Thanks for your feedback

**Comment by joel16** [comment]
Hey, sorry for such a late response but certain services used by 3DShell makes it impossible to be used on *hax. Does FBI work fine?

**Comment by joel16** [comment]
Closing this due to lack of feedback.

**Comment by diegofn** [comment]
No problem @joel16 my 3DS does not have FBI or custom firmware. It only has *hax.
