### ISSUE TITLE
FTP requires hard reset when used for a second time.

### ISSUE THREAD

**Issue by joel16** [joel16/3DShell#4]
Basically if you use the FTP through the app, and then disable it. Everything's fine, and you can exit without any crashes. However, if you use the ftp button twice. You turn on ftp, disable it, then turn it on again (without exiting the app) and disable it. At this point pressing start (to exit) or pressing the home button triggers a crash,

@mtheall do you know what could possibly cause this? FTPD at least exits the app once you've pressed B on it, so there's not really any way to reactivate FTP again without exiting the app. I'm just wondering if there's something in ftp.c that fails to re-initialize or something. (Thanks for the code btw, I tried implementing FTP myself, but me and networking don't go well together, so I thought I'd use something clean and well supported.)

References: 

ftp.c https://github.com/joel16/3DShell/blob/master/source/ftp.c
main.c https://github.com/joel16/3DShell/blob/master/source/main.c#L483 This line is where FTP is handled.

Please let me know if I'm doing something wrong.

**Comment by mtheall** [comment]
I'll take a look when I get a chance. Is the ftp code lifted as-is or are there some mods?

It would be useful if you can mark the source code's origin and mark specific modifications.

**Comment by joel16** [comment]
Well, in ftp it's entirely all yours except for the console rendering/printing stuff, had to remove those to make it suit the GUI. There are very little differences, mainly those being in ftp where you'd check if KEY_B is pressed, mine uses a touch instead. Apart from that there isn't anything really. Also, mine doesn't use the wait for B loop, it handles that in ftp.c directly. 

I can comment my modifications and push a commit tomorrow morning if that helps. Thanks for looking into this.

**Comment by joel16** [comment]
Alright so I've updated the source with your latest changes, and indicated modification. https://github.com/joel16/3DShell/commit/631d3c70d86446ab1d098b178a0ade7a5c7a1f97

In main.c https://github.com/joel16/3DShell/blob/631d3c70d86446ab1d098b178a0ade7a5c7a1f97/source/main.c#L475 from lines 475 to 502 is where FTP can be activated/reactivated

And this is my loop function: https://github.com/joel16/3DShell/blob/631d3c70d86446ab1d098b178a0ade7a5c7a1f97/source/main.c#L313.

**Comment by joel16** [comment]
Heh, fixed. https://github.com/joel16/3DShell/commit/f52778acba4efe6fa0cd140c41e550962fd76b48
