### ISSUE TITLE
[Feature Request] Add support for nintendo music formats. 

### ISSUE THREAD

**Issue by frozenLake** [joel16/3DShell#40]
Specifically formats such as BCWAV, BCSTM, ect.

I know this is already included in the post I made for the hex/text editor, but I figured that it would be a wise idea to seperate the two requests.

**Comment by joel16** [comment]
I did give this a go at one point, but it was too much of a pain and decided not to. One implementation (like in freeshop) seems to work fine on some devices, but just doesn't work on others.

Short answer: Won't happen unless someone else is willing to PR this, sorry.
