### ISSUE TITLE
Feature Request : Json Updater

### ISSUE THREAD

**Issue by Volti-p** [joel16/3DShell#41]
Hey, is it possible, to add a Updater like Multi Updater to 3DShell? That would be great, because we can have then a `config.json` file, that has the links and the Ordner Structure inside it like Multi Updater ^^ I would like it, if this is possible :)

**Comment by Volti-p** [comment]
With Multiupdater do i mean this : https://github.com/LiquidFenrir/MultiUpdater  Maybe you can Import somethings from it :D

**Comment by joel16** [comment]
This is not in scope of this project.
