### ISSUE TITLE
Feature Request: Ability to create file-type specific plugins

### ISSUE THREAD

**Issue by badda71** [joel16/3DShell#46]
A great feature (for users as well as for developers) would be the support of file-type specific plugins. These plugins could be developed and installed separately from the main 3DShell application. 3DShell would have to maintain a mapping of file type (or filename extension) to plugin and would call this plugin whenever the user selects a file with a certain actions (e.g. "preview", "view", "edit", ...).
This way, a developer could develop a plugin for viewing e.g. Excel-sheets without bloating the main 3DShell application. The user, on the other hand, could choose which plugins to install depending on the files he stores on his 3DS. Thinkable would also be an online plugin-repository in which 3DShell could load missing plugins when the user selects an unassociated file type.
Most of the current feature requests could be delegated to plugin-writers this way, too :-)
What do you think about that?

**Comment by joel16** [comment]
It sounds like a great idea but it's out of scope of this project at the moment. That being said PRs are always welcome.
