### ISSUE TITLE
[Feature] Page Up/Page Down controls when browsing a folder

### ISSUE THREAD

**Issue by SadisticMystic** [joel16/3DShell#47]
Currently, it's possible to scroll through a folder view with four types of input: D-pad up (scroll up 1 item), D-pad down (scroll down 1 item), D-pad left (scroll all the way up to the first item in the folder), and D-pad right (scroll all the way down to the last item in the folder). When you're looking for one thing in a large folder, this leaves you with no choice but to scroll through the entire list one item at a time, which can take a while depending on how big the list actually is.

My thought is to add buttons for scrolling by 5 at a time, as many as will fit on one screen full. L and R will be free for this at times when the folder view is what's capturing inputs.

**Comment by joel16** [comment]
Fixed with latest beta release.
