### ISSUE TITLE
Deleting a single file deletes cfw files from root of sd

### ISSUE THREAD

**Issue by xXPVTSnowBallXx** [joel16/3DShell#48]
I dont know why but this is the 2nd time its happened, I installed luma cfw to my n3ds xl and after installing a theme with anemone I used 3dshell to delete one of themes i didnt like, and it didnt just delete the one file i selected, it deletes my cfw files on the root of my sd as well. The 2nd time i even made sure i didnt select anything other than the desired file.

**Comment by joel16** [comment]
By select do you actually select it using the Y button? If you're selecting one file or folder you don't need to use multi-select. However this is a rather weird issue and I don't know what could possibly cause this. Does it only delete the CFW files?

**Comment by xXPVTSnowBallXx** [comment]
Yes i was using y, but i reinstalled 3dshell and it seems to be working properly now. Sorry and thanks for the time though, it just seemed like an oddly specific issue to be from a bad install
