### ISSUE TITLE
MP3 Files show information, but don't play

### ISSUE THREAD

**Issue by JoeJoeTV** [joel16/3DShell#50]
I have mp3 files in a folder(300+ files CBR 320 kbits) and when I select any of them, it show the title, year, etc, and even the cover art, but doesn't play. It just stays at 00:00.

**Comment by joel16** [comment]
I've decided to remove the audio decoder functionality within 3DShell due to lack of time, and motivation. You can use the following alternative which seems to be better supported: https://github.com/Oreo639/LimePlayer3DS
