### ISSUE TITLE
Corrupted Home Menu Extdata???

### ISSUE THREAD

**Issue by user843681** [joel16/3DShell#51]
I have an o2DS on firmware 11.10.0-43U. I installed the latest version of 3DShell. I messed around with renaming and stuff and looked at all the other features in the app.
And so I decided to use the media player. I got a bunch of .mp3 files, put them on my SD card, and used 3DShell to play them. I put my o2ds into sleep mode a bunch of times, changed the volume a lot, and turned the Loop and Shuffle features on and off over and over.
I navigated back to the root of my SD card in the app, tapped the little gear icon, and then pressed START to go back to the Home Menu.
My o2DS showed a few random colored pixels in the corner which always happens when exiting from Homebrew with START, and then it just froze. I waited about ten seconds, and then proceeded to open the Rosalina menu and select the Power Off option, which did nothing.
So I turned off my o2DS forcefully by pressing and holding the Power Off button for about ten seconds. It turned off, and so I turned it back on. My splash was skipped, the blue light was on, but the Home Menu didn't load. I turned it off and back on. The splash loaded, the blue and orange lights turned on, but the Home Menu didn't load.
So, I went online and found this issue on GBATemp: https://gbatemp.net/threads/what-is-wrong-with-my-2ds-it-cant-boot-to-home-menu.506674/
One user suggested deleting the Home Menu extdata, so that's what I did.
And voila, my o2Ds was revived, but all of my 50+ apps were wrapped up in presents again unfortunately.
I'm not sure if what happened is my fault, completely unrelated to 3DShell, or because of 3DShell, but I just thought that I should warn others.
I also thought I would just let the creator of this know, even though I doubt this is still being worked on.

**Comment by joel16** [comment]
"I messed around with renaming and stuff"
Sounds more like a user error. No one's reported such an issue and I have no way to reproduce this. Music player doesn't modify any files so I can rule that out.
