### ISSUE TITLE
[Feature] M4A Support

### ISSUE THREAD

**Issue by V10lator** [joel16/3DShell#53]
It would be great to be able to play mp4/aac audio. There are multiple libraries around:

- https://github.com/mstorsjo/fdk-aac - Used in Android but not sure if the license is GPL compatible.
- FAAD2 ( https://www.audiocoding.com/downloads.html ) - GPL licensed, so should be no problem to use it in 3DShell.

There are more but I don't think the others will be of much use here.

**Comment by joel16** [comment]
I've decided to remove the audio decoder functionality within 3DShell due to lack of time, and motivation. You can use the following alternative which seems to be better supported: https://github.com/Oreo639/LimePlayer3DS
