### ISSUE TITLE
Compile error: 'SDMC_DIRITER_MAGIC' undeclared

### ISSUE THREAD

**Issue by xpirad** [joel16/3DShell#54]
When i'm compiling 3dshell, i met the same problem when compiling ftpd.
Could you update ftp module of 3dshell to a more recent version?

I raised this issue a bit earlier:
https://github.com/mtheall/ftpd/issues/106

**Comment by joel16** [comment]
Fixed with https://github.com/joel16/3DShell/commit/989db6b237e9ddf73e69ba078e03d832b31705d9
