### ISSUE TITLE
Crashes upon trying to play MP3. Any MP3.

### ISSUE THREAD

**Issue by plasmaster09** [joel16/3DShell#55]
Self-explanatory- upon trying to play an MP3 file (the files in question all work in ctrmus and 3DS Sound + Music), it crashes my 3ds.
I tried messing with Luma's settings to fix it, and nothing worked.

**Comment by joel16** [comment]
I've decided to remove the audio decoder functionality within 3DShell due to lack of time, and motivation. You can use the following alternative which seems to be better supported: https://github.com/Oreo639/LimePlayer3DS

**Comment by plasmaster09** [comment]
> I've decided to remove the audio decoder functionality within 3DShell due to lack of time, and motivation. You can use the following alternative which seems to be better supported: https://github.com/Oreo639/LimePlayer3DS

That explains it. (I hope LimePlayer has a loop function.)
