### ISSUE TITLE
installation trouble

### ISSUE THREAD

**Issue by FireXDragon007** [joel16/3DShell#56]
I'm new to this whole modding thing for the 3DS, I can't quite grasp the details on what I should do to install 3dshell, I just know the basics of downloading and installing CIAs. But this requires messing around with source code and I'm not familiar with that if there is a video on how to install this I would appreciate a link, thanks

**Comment by deltabeard** [comment]
You can download the latest CIA build from the releases page, under the "Assets" section for each release. https://github.com/joel16/3DShell/releases
