### ISSUE TITLE
Sounds not sequential when play MP3 with high bitrate

### ISSUE THREAD

**Issue by CyberRex0** [joel16/3DShell#57]
I played MP3 320kbps, but sounds is not sequential.
It looks processing is too slow.

**Comment by joel16** [comment]
I haven't worked on this in ages, but I know at some point I unfortunately screwed up the audio decoder. I don't know if I'll get back to this because I can't even find my 3ds.

**Comment by joel16** [comment]
I've decided to remove the audio decoder functionality within 3DShell due to lack of time, and motivation. You can use the following alternative which seems to be better supported: https://github.com/Oreo639/LimePlayer3DS
