### ISSUE TITLE
Certain sizes of images crashes 3DShell

### ISSUE THREAD

**Issue by DimensionShifter** [joel16/3DShell#64]
When I try and load different images (pngs and jpgs) in different dimensions, some sizes crash the program. Other sizes that are extremely tall tend not to show up at all. The crashing issue exists within ORGANIZ3R too, does it have something to do with the O3DS not being able to handle some sizes of pngs/jpgs?

The exception type and fault status that pops up after crashing is "data abort", "Translation - Section"

**Comment by joel16** [comment]
I believe there is a limit to the texture size, I can't exactly recall what it was. Also, I haven't been working on this application for a while now and I'm not sure if I will anytime soon.

**Comment by joel16** [comment]
Doesn't happen with the current release.
