### ISSUE TITLE
XML file is recognized as a music file

### ISSUE THREAD

**Issue by ghost** [joel16/3DShell#68]
###### Use Google Translate

As the title suggests, **the xml file is recognized as a music file**. Also, playing will destroy the seek bar, and if you played a music file just before, only a small part of that music file will always loop.
Autoplay works fine.
The attached image is the image when the xml file is played.
![mrg_2021-02-13_14-50-45 050](https://user-images.githubusercontent.com/49714268/107844620-52a8d980-6e18-11eb-9ced-dea71eccafd1.jpeg)

Request a fix.

**Comment by joel16** [comment]
This is a bug in the old release that is no longer being supported.
