### ISSUE TITLE
Enable BGM upon startup won't work

### ISSUE THREAD

**Issue by CecilFF4** [joel16/3DShell#7]
The button for enabling BGM stays off, no matter where I press. There is a valid bgm.ogg in the 3ds/3dshell folder, too. Running 2.0 beta.

**Comment by joel16** [comment]
The button was disabled due to certain restrictions. That's why the font colour is gray for that option. I'll close this for now, because I'm aware of the problem and the button being grayed out was intentional. I'll have to work on this later.
