### ISSUE TITLE
[BUG] Unwanted File Deletion

### ISSUE THREAD

**Issue by ghost** [joel16/3DShell#71]
So, this has actually happened twice recently, I thought I might have done something wrong the first time, but when it happened again, I knew there was an issue. So I was deleting some screenshots from /luma/screenshots, and I had selected about half of them. I then clicked the delete button. It returned an error (umfortunately I was panicked at the time and forgot to write down the exact details) that mentioned something about a file system error, and then 3DShell froze. I then realized that the entire "luma" folder had had its contents removed! I've done the exact same procedure on different file managers, though, and it has worked perfectly fine. So, since this probably won't be fixed, anyone reading this would be well advised to back up a folder before mass deleting parts of the folder if using 3DShell.

**Comment by joel16** [comment]
This was fixed in the most recent update.
