### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by CecilFF4** [joel16/3DShell#8]
I'd love to have one app to rule them all, so I do compare this to features of other apps that I use often. For instance, the FTP seems to work a bit better in 3DShell than it does in FTPDB. But there are other areas of the app that I think could benefit from some or all of these suggestions:

- Button to swap screens so we can scroll and tap files via touch screen.
- Faster scroll using left/right.
- Common file operations given key shortcuts (Y = copy, X = delete, etc.) -- see Godmode9 for more details.
- Enable changing font size and/or distance between items in the file list.
- Enable sorting of files by different properties (i.e. sorting folders first/files second and sorting them all alphabetically would be better than the current sorting of date created, imo, especially since a lot of homebrew doesn't write correct dates).
- Play music files. Maybe even with support for bcstm.
- Randomized theming, including random music selection, for those of us who like something different every startup.
- Ability to select music of any name (in 3ds/3dshell/music ??) as the bgm.

This program has a LOT of potential. And the interface looks pretty good so far. Can't wait to see what it turns into.

**Comment by joel16** [comment]
That's a lot of suggestions. I'm not sure if I'll have the time to do all of them, but I'll definitely consider it, thanks.

**Comment by CookieXD** [comment]
would it be possible to get direct access to the ctr nand via ftp?

**Comment by joel16** [comment]
I doubt it since we aren't using FS:User for FTP.

**Comment by pixelmasher** [comment]
Could this be incorporated?
https://github.com/LiquidFenrir/LocalFileShare
It would be cool to transfer files between 2/3DS from 3DShell.

**Comment by joel16** [comment]
Hmm, haven't looked into it but I'm sure it could be implemented. Although I'm really busy with college right now so I won't be able to do anything until mid December. I'll definitely try to make a release then.

**Comment by CecilFF4** [comment]
Just wanted to say thanks for the latest release! Looking good!

**Comment by joel16** [comment]
Gonna close this as most of the things I wanted to implement from these suggestions have been done.

**Comment by CecilFF4** [comment]
Thanks for your hard work!
