### ISSUE TITLE
Renaming doesn't stick. 

### ISSUE THREAD

**Issue by KevinBlue18** [joel16/3DShell#9]
I love your work in the Vita and 3DS scene, but renaming in 3DShell doesn't stay.

**Comment by joel16** [comment]
What exactly do you mean by it doesn't stay?

I just tested rename on a zip file and it worked just fine here. What file are you trying to rename?

**Comment by KevinBlue18** [comment]
Oh sorry I mean renaming folders

**Comment by joel16** [comment]
My bad you're correct. I must have missed it since I only tested renaming on an empty folder, which is treated as a file and so it will rename it correctly.

Anyways I've added the folder check and fixed it now. https://github.com/joel16/3DShell/commit/1df492e33a283e4e4715c24d87bda5fba4336cb8
